---
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"

sudo: false

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=ember-2.4
  - EMBER_TRY_SCENARIO=ember-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - ALLOW_DEPRECATIONS=TRUE EMBER_TRY_SCENARIO=ember-beta
  - ALLOW_DEPRECATIONS=TRUE EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: ALLOW_DEPRECATIONS=TRUE EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g yarn
  - npm install phantomjs-prebuilt
  - yarn global add greenkeeper-lockfile@1

install:
  - yarn --no-lockfile

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
